package db.migration;


import com.system.db.entity.Entity;
import com.system.db.migration.table.TableCreationMigration;
import com.system.export.content.definition.SystemExportContentDefinition;
import com.system.export.generator.SystemExportGenerator;
import com.system.export.generator.content.SystemExportGeneratorContent;
import com.system.util.collection.CollectionUtils;

import java.util.List;

/**
 * The <class>V8__content_schema</class> defines an entity which records
 * the content generated by a {@link SystemExportGenerator}
 *
 * @author Andrew
 */
public class V8__content_schema extends TableCreationMigration {

    ///////////////////////////////////////////////////////////////////////
    ////////                                                     Properties                                                       //////////
    //////////////////////////////////////////////////////////////////////


    ///////////////////////////////////////////////////////////////////////
    ////////                                                 Table Creation                                                  //////////
    //////////////////////////////////////////////////////////////////////

    protected List<Class<? extends Entity>> getEntityClasses() {
        return CollectionUtils.asList(
                SystemExportContentDefinition.class, SystemExportGeneratorContent.class
        );
    }

    ///////////////////////////////////////////////////////////////////////
    ////////                                                  Data Insertion                                                   //////////
    //////////////////////////////////////////////////////////////////////

    @Override
    protected void insertData() {
    }

    ///////////////////////////////////////////////////////////////////////
    ////////                                             Basic   Getter/Setters                                          //////////
    //////////////////////////////////////////////////////////////////////

}