package com.system.logging.exception;

/**
 * The <class>SystemException</class> defines
 * the basic System Exception wrapper to other exceptions
 * throughout the system. This is useful for translating errors
 * ,generated by system logic, to the UI user in a friendly readable way
 * or for use in logging.
 *
 * @author Andrew
 */
public class SystemException extends RuntimeException {

    ///////////////////////////////////////////////////////////////////////
    ////////                                                     Properties                                                       //////////
    //////////////////////////////////////////////////////////////////////

    /**
     * A friendly status code that we can use to return to the client UI.
     * This should be a regular system enum and not related to spring packages
     */
    private String status;

    /**
     * A reason header describing why this exception happened, usually technical in nature and not often used beyond logging purposes
     */
    private String reason;

    ///////////////////////////////////////////////////////////////////////
    ////////                                              Default Constructor                                           //////////
    //////////////////////////////////////////////////////////////////////

    public SystemException(String status, String reason, String message, Throwable cause) {
        super(message, cause);
        this.status = status;
        this.reason = reason;
    }

    public static SystemException newInstance(String status, String reason, String message, Throwable cause) {
        return new SystemException(status, reason, message, cause);
    }

    public static SystemException newInstance(String message, Throwable cause) {
        return SystemException.newInstance("417", "Expectation Failed", message, cause);
    }

    public static SystemException newInstance(String message) {
        return SystemException.newInstance(message, null);
    }

    ///////////////////////////////////////////////////////////////////////
    ////////                                             Basic   Getter/Setters                                          //////////
    //////////////////////////////////////////////////////////////////////

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }
}
